-- Built-in reusable equipment, explicitly granted by the companion rules.
-- Consumable building materials and fuel are not generated by this module.
local Tools = {}
-- Every identifier below resolves enabled/non-obsolete in the exact installed
-- Build 42.20.4 item registry captured in reference/pz-items.json. Keep this
-- allowlist limited to reusable equipment; materials, fluids, batteries and
-- repair inputs are intentionally absent.
Tools.types={
    -- Access / breach.
    "Base.Crowbar","Base.BoltCutters","Base.Sledgehammer","Base.Axe","Base.HandAxe",
    -- Carpentry.
    "Base.Hammer","Base.Saw","Base.Screwdriver","Base.HandDrill","Base.File",
    -- Mechanics.
    "Base.Wrench","Base.PipeWrench","Base.LugWrench","Base.Jack","Base.TirePump",
    "Base.CarBatteryCharger",
    -- Metalwork.
    "Base.BlowTorch","Base.WeldingMask","Base.BallPeenHammer","Base.MetalworkingPliers",
    "Base.Tongs","Base.SheetMetalSnips","Base.MetalworkingChisel",
    -- Farming and general survival.
    "Base.Shovel","Base.HandShovel","Base.GardenHoe","Base.Scythe","Base.Needle",
    "Base.Scissors"
}
local allowed={}
for _,kind in ipairs(Tools.types) do allowed[kind]=true end

local function call(object,method,...)
    if object==nil then return false end
    local ok,member=pcall(function() return object[method] end)
    if not ok or type(member)~="function" then return false end
    return pcall(member,object,...)
end

function Tools.reserved(item)
    local _,data=call(item,"getModData")
    return data and data.GoblinToolKit==true or false
end

function Tools.ensure(body,kind,recipeInput,copyNumber)
    copyNumber=copyNumber or 1
    local _,data=call(body,"getModData")
    if not data or data.GoblinNPC~=true then return nil end
    if recipeInput or not allowed[kind] then
        -- Only the installed recipe's reusable tool slot may extend the kit.
        -- A model-provided item name alone can never grant an arbitrary item.
        local keepOK,keep=call(recipeInput,"isKeep")
        local toolOK,isTool=call(recipeInput,"isTool")
        local matched=false
        local _,choices=call(recipeInput,"getPossibleInputItems")
        local _,n=call(choices,"size")
        for i=0,(tonumber(n) or 0)-1 do
            local _,scriptItem=call(choices,"get",i)
            if select(2,call(scriptItem,"getFullName"))==kind then matched=true;break end
        end
        if not keepOK or not keep or not toolOK or not isTool or not matched then return nil end
    end
    local limit=1
    if select(2,call(recipeInput,"isItemCount"))==true then limit=select(2,call(recipeInput,"getAmount")) end
    if type(limit)~="number" or limit~=math.floor(limit) or limit<1 or limit>32
        or type(copyNumber)~="number" or copyNumber~=math.floor(copyNumber) or copyNumber<1 or copyNumber>limit then return nil end
    local _,inventory=call(body,"getInventory")
    local _,items=call(inventory,"getItems")
    local _,size=call(items,"size")
    local tool,seen=nil,0
    for i=0,(tonumber(size) or 0)-1 do
        local _,item=call(items,"get",i)
        local _,fullType=call(item,"getFullType")
        if fullType==kind and Tools.reserved(item) then
            seen=seen+1
            if seen==copyNumber then tool=item;break end
        end
    end
    if not tool then
        local _,created=call(inventory,"AddItem",kind)
        tool=created
        local _,metadata=call(tool,"getModData")
        if not metadata then
            if tool then call(inventory,"Remove",tool) end
            return nil
        end
        -- Supplying the tool must not also mint fuel on every empty-tool replacement.
        -- Verify native mutation: a missing, throwing or ineffective setter must
        -- not leave a newly supplied full fuel container in the reserved kit.
        local emptied=true
        if select(2,call(tool,"IsDrainable")) then
            local changed=call(tool,"setCurrentUses",0)
            local read,uses=call(tool,"getCurrentUsesFloat")
            emptied=changed and read and uses==0
        end
        local _,fluid=call(tool,"getFluidContainer")
        if fluid then
            local changed=call(fluid,"adjustAmount",0)
            local read,amount=call(fluid,"getAmount")
            emptied=emptied and changed and read and amount==0
        end
        if not emptied then call(inventory,"Remove",tool);return nil end
        metadata.GoblinToolKit=true
    end
    local _,maximum=call(tool,"getConditionMax")
    if type(maximum)=="number" then
        local changed=call(tool,"setCondition",maximum)
        local read,condition=call(tool,"getCondition")
        -- Keep the reserved item on failure so retries neither duplicate it
        -- nor discard fuel acquired later. A failed repair is not readiness.
        if not changed or not read or condition~=maximum then return nil end
    end
    return tool
end

function Tools.ensureKit(body)
    local _,data=call(body,"getModData")
    if not data or data.GoblinNPC~=true then return false,0 end
    local _,inventory=call(body,"getInventory")
    local _,capacity=call(inventory,"getCapacity")
    if type(capacity)=="number" and capacity<100 then call(inventory,"setCapacity",100) end
    local _,maxWeight=call(body,"getMaxWeight")
    if type(maxWeight)=="number" and maxWeight<100 then call(body,"setMaxWeight",100) end
    local count=0
    for _,kind in ipairs(Tools.types) do if Tools.ensure(body,kind) then count=count+1 end end
    return count==#Tools.types,count
end

return Tools
